---
title: The Complete Guide to Reproducible Data Practices in R
author: John-Henry
date: '2019-02-14'
slug: the-complete-guide-to-reproducible-data-practices-in-r
categories:
  - Blog
tags:
  - Rstats
  - OpenScience
subtitle: ''
description: ''
image: ''
draft: yes
---

[Open science practices are on the rise](https://youtu.be/tK03lp47w-I). However I don't really think good coding practices are there yet. There are a few really [good](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/) [guides](https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf) on good workflow practices that I found especially helpful, but nothing modern or comprehensive (or entirely focused in R!). This is my attempt at such a guide.

Before going further I do want to emphasize that it makes sense to post data and code to a place like [OSF](osf.io). Academics move institutions which causes links, people forget to renew personal websites. A place like OSF has their reputation on the line to keep these links absolute. Make it their problem not yours. [Uri Simonsohn also has a guide specifically about keeping website links alive for those interested](http://datacolada.org/34).


## Managing Working Directory


## Package Dependency
As I told my lab 

## Dynamic Documents


### References


### Misc Tips
